---
language: python
services: docker

env:
  global:
    - ROLE_NAME: snmp
  matrix:
    - MOLECULE_DISTRO: centos6
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: debian10

install:
  - pip install docker molecule yamllint ansible-lint flake8
  - git clone https://github.com/arillso/tests molecule/default/lint

before_script:
  - cd ../
  - mv ansible.$ROLE_NAME sbaerlocher.$ROLE_NAME
  - cd sbaerlocher.$ROLE_NAME

script:
  - molecule test

notifications:
  webhooks:
    urls:
      - https://galaxy.ansible.com/api/v1/notifications/
    on_success: always
  email:
    on_success: never
    on_failure: always
