---
# tasks file for sbaerlocher.snmp

- name: Check DSC Feature state
  community.windows.win_feature_info:
    name: "{{  snmp_dsc_name }}"
  register: dsc_feature_info

- name: Set fact DSC install state
  set_fact:
    dsc_install_status: "{{ dsc_feature_info | json_query(dsc_state_query) | bool }}"
  vars:
    dsc_state_query: "[*].installed"

- name: 'windows : install SNMP with DSC'
  win_dsc:
    resource_name: "{{ snmp_resource_name }}"
    Name: "{{ snmp_name }}"
    Ensure: "{{ snmp_present }}"
  when: ansible_powershell_version >= 5 and dsc_install_status

- name: 'windows : install SNMP without DSC'
  win_feature:
    name: "{{ snmp_name }}"
    state: "{{ snmp_present }}"
  when: ansible_powershell_version <= 5 and not dsc_install_status

- name: 'windows : setting SNMP'
  win_regedit:
    path: 'HKLM:\\SYSTEM\\CurrentControlSet\\Services\\SNMP\\Parameters\\{{ item.path }}'
    name: '{{ item.name }}'
    type: '{{ item.type }}'
    data: '{{ item.data }}'
  with_items:
    - path: PermittedManagers
      name: '1'
      type: string
      data: '{{ snmp_access_address | default() }}'
    - path: RFC1156Agent
      name: sysContact
      type: string
      data: '{{ snmp_contact | default() }}'
    - path: RFC1156Agent
      name: sysLocation
      type: string
      data: '{{ snmp_location | default() }}'
    - path: ValidCommunities
      name: '{{ snmp_community | default() }}'
      type: dword
      data: '4'
  notify:
    - restart win snmp

- name: 'windows : set remote IP-Address'
  set_fact:
    snmp_remoteip: "{{ lookup('dig', snmp_monitoring_server ) }}"
  when: not snmp_monitoring_server | ipaddr

- name: 'windows : firewall rule to allow ICMP'
  win_firewall_rule:
    name: ICMP
    action: allow
    direction: in
    protocol: ICMPv4
    remoteip: '{{ snmp_remoteip | default( snmp_monitoring_server ) }}'
    state: present
    enabled: true

- name: 'windows : firewall rule to allow SNMP-Service'
  win_firewall_rule:
    name: SNMP
    action: allow
    direction: in
    protocol: UDP
    localport: '161'
    remoteip: '{{ snmp_remoteip | default( snmp_monitoring_server ) }}'
    state: present
    enabled: true